# Generated by Django 5.0 on 2024-01-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0005_alter_accountmodel_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountmodel',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=12, null=True),
        ),
    ]
