# Generated by Django 5.0 on 2024-01-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0009_orderbooks_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbooks',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
