# Generated by Django 5.0 on 2024-01-25 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0010_remove_orderbooks_is_paid_accountmodel_is_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountmodel',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='booksmodel',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
