# Generated by Django 5.0 on 2024-01-25 11:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0012_review_delete_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
