# Generated by Django 5.0 on 2024-01-25 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0013_review_order_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='order_date',
            new_name='created_on',
        ),
    ]
