# Generated by Django 5.0 on 2024-01-25 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookApp', '0015_review_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booksmodel',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='orderbooks',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
